spring:
  datasource:
    url: jdbc:mysql://remotemysql.com:3306/tjMqgYOVqy
    username: tjMqgYOVqy
    password: rq5YslKAcb
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: false
  profiles.active: dev
server:
  port: 8080


